/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zkHarvestErc20ProxySol from "./ZKHarvestERC20Proxy.sol";
export type { zkHarvestErc20ProxySol };
export type { ZKHFactoryProxy } from "./ZKHFactoryProxy";
export type { ZKHLockerProxy } from "./ZKHLockerProxy";
export type { ZKHMasterProxy } from "./ZKHMasterProxy";
export type { ZKHPairProxy } from "./ZKHPairProxy";
export type { ZKHRouterProxy } from "./ZKHRouterProxy";
export type { ZKHTokenProxy } from "./ZKHTokenProxy";
export type { ZKHTreasurerProxy } from "./ZKHTreasurerProxy";
